//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.25 at 10:03:04 ?�후 KST 
//

package com.jcone.rmsXmlCmd.common.utils.marshalling;

import javax.xml.bind.annotation.XmlRegistry;

import com.jcone.rmsXmlCmd.common.utils.marshalling.WorkRoot.ParamList;
import com.jcone.rmsXmlCmd.common.utils.marshalling.WorkRoot.ReceiveInfo;
import com.jcone.rmsXmlCmd.common.utils.marshalling.WorkRoot.ReturnList;
import com.jcone.rmsXmlCmd.common.utils.marshalling.WorkRoot.SendInfo;
import com.jcone.rmsXmlCmd.common.utils.marshalling.WorkRoot.WorkInfo;
import com.jcone.rmsXmlCmd.common.utils.marshalling.WorkRoot.ParamList.Param;
import com.jcone.rmsXmlCmd.common.utils.marshalling.WorkRoot.ReturnList.ReturnRow;
import com.jcone.rmsXmlCmd.common.utils.marshalling.WorkRoot.ReturnList.ReturnRow.ReturnCol;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.google.code.j2eeshowcases.jaxbgen.unmarshalling package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.google.code.j2eeshowcases.jaxbgen.unmarshalling
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SendInfo }
     * 
     */
    public SendInfo createWorkRootSendInfo() {
        return new SendInfo();
    }

    /**
     * Create an instance of {@link Param }
     * 
     */
    public Param createWorkRootParamListParam() {
        return new Param();
    }

    /**
     * Create an instance of {@link ReturnRow }
     * 
     */
    public ReturnRow createWorkRootReturnListReturnRow() {
        return new ReturnRow();
    }

    /**
     * Create an instance of {@link ReceiveInfo }
     * 
     */
    public ReceiveInfo createWorkRootReceiveInfo() {
        return new ReceiveInfo();
    }

    /**
     * Create an instance of {@link ParamList }
     * 
     */
    public ParamList createWorkRootParamList() {
        return new ParamList();
    }

    /**
     * Create an instance of {@link ReturnCol }
     * 
     */
    public ReturnCol createWorkRootReturnListReturnRowReturnCol() {
        return new ReturnCol();
    }

    /**
     * Create an instance of {@link WorkInfo }
     * 
     */
    public WorkInfo createWorkRootWorkInfo() {
        return new WorkInfo();
    }

    /**
     * Create an instance of {@link ReturnList }
     * 
     */
    public ReturnList createWorkRootReturnList() {
        return new ReturnList();
    }

    /**
     * Create an instance of {@link WorkRoot }
     * 
     */
    public WorkRoot createWorkRoot() {
        return new WorkRoot();
    }

}
