//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.25 at 10:03:04 ?�후 KST 
//


package com.jcone.rmsXmlCmd.common.utils.marshalling;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

import com.jcone.rmsXmlCmd.common.utils.marshalling.WorkRoot.ParamList;
import com.jcone.rmsXmlCmd.common.utils.marshalling.WorkRoot.ReceiveInfo;
import com.jcone.rmsXmlCmd.common.utils.marshalling.WorkRoot.ReturnList;
import com.jcone.rmsXmlCmd.common.utils.marshalling.WorkRoot.SendInfo;
import com.jcone.rmsXmlCmd.common.utils.marshalling.WorkRoot.WorkInfo;
import com.jcone.rmsXmlCmd.common.utils.marshalling.WorkRoot.ParamList.Param;
import com.jcone.rmsXmlCmd.common.utils.marshalling.WorkRoot.ReturnList.ReturnRow;
import com.jcone.rmsXmlCmd.common.utils.marshalling.WorkRoot.ReturnList.ReturnRow.ReturnCol;


/**
 * <p>Java class for work_root element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="work_root">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="work_info">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="work_key" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="work_div" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="work_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="send_info">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;attribute name="ip" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                   &lt;attribute name="port" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="receive_info">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;attribute name="ip" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                   &lt;attribute name="port" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="param_list" maxOccurs="unbounded" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="param" maxOccurs="unbounded" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;simpleContent>
 *                           &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                             &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;/extension>
 *                         &lt;/simpleContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/sequence>
 *                   &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="return_list" maxOccurs="unbounded" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="return_row" maxOccurs="unbounded" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="return_col" maxOccurs="unbounded" minOccurs="0">
 *                                 &lt;complexType>
 *                                   &lt;simpleContent>
 *                                     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;/extension>
 *                                   &lt;/simpleContent>
 *                                 &lt;/complexType>
 *                               &lt;/element>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/sequence>
 *                   &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "workInfo",
    "sendInfo",
    "receiveInfo",
    "paramList",
    "returnList"
})
@XmlRootElement(name = "work_root")
public class WorkRoot {

    /**
	 * @uml.property  name="workInfo"
	 * @uml.associationEnd  
	 */
    @XmlElement(name = "work_info", required = true)
    protected WorkInfo workInfo;
    /**
	 * @uml.property  name="sendInfo"
	 * @uml.associationEnd  
	 */
    @XmlElement(name = "send_info", required = true)
    protected SendInfo sendInfo;
    /**
	 * @uml.property  name="receiveInfo"
	 * @uml.associationEnd  
	 */
    @XmlElement(name = "receive_info", required = true)
    protected ReceiveInfo receiveInfo;
    /**
	 * @uml.property  name="paramList"
	 * @uml.associationEnd  multiplicity="(0 -1)" elementType="com.jcone.rmsXmlCmd.common.utils.marshalling.WorkRoot$ParamList"
	 */
    @XmlElement(name = "param_list", required = true)
    protected List<ParamList> paramList;
    /**
	 * @uml.property  name="returnList"
	 * @uml.associationEnd  multiplicity="(0 -1)" elementType="com.jcone.rmsXmlCmd.common.utils.marshalling.WorkRoot$ReturnList"
	 */
    @XmlElement(name = "return_list", required = true)
    protected List<ReturnList> returnList;

    /**
	 * Gets the value of the workInfo property.
	 * @return  possible object is {@link WorkInfo  }  
	 */
    public WorkInfo getWorkInfo() {
        return workInfo;
    }

    /**
	 * Sets the value of the workInfo property.
	 * @param value  allowed object is {@link WorkInfo  }  
	 */
    public void setWorkInfo(WorkInfo value) {
        this.workInfo = value;
    }

    /**
	 * Gets the value of the sendInfo property.
	 * @return  possible object is {@link SendInfo  }  
	 */
    public SendInfo getSendInfo() {
        return sendInfo;
    }

    /**
	 * Sets the value of the sendInfo property.
	 * @param value  allowed object is {@link SendInfo  }  
	 */
    public void setSendInfo(SendInfo value) {
        this.sendInfo = value;
    }

    /**
	 * Gets the value of the receiveInfo property.
	 * @return  possible object is {@link ReceiveInfo  }  
	 */
    public ReceiveInfo getReceiveInfo() {
        return receiveInfo;
    }

    /**
	 * Sets the value of the receiveInfo property.
	 * @param value  allowed object is {@link ReceiveInfo  }  
	 */
    public void setReceiveInfo(ReceiveInfo value) {
        this.receiveInfo = value;
    }

    /**
     * Gets the value of the paramList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the paramList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParamList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ParamList }
     * 
     * 
     */
    public List<ParamList> getParamList() {
        if (paramList == null) {
            paramList = new ArrayList<ParamList>();
        }
        return this.paramList;
    }

    /**
     * Gets the value of the returnList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the returnList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReturnList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReturnList }
     * 
     * 
     */
    public List<ReturnList> getReturnList() {
        if (returnList == null) {
            returnList = new ArrayList<ReturnList>();
        }
        return this.returnList;
    }


    /**
	 * <p>Java class for anonymous complex type. <p>The following schema fragment specifies the expected content contained within this class. <pre> &lt;complexType> &lt;complexContent> &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"> &lt;sequence> &lt;element name="param" maxOccurs="unbounded" minOccurs="0"> &lt;complexType> &lt;simpleContent> &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string"> &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /> &lt;/extension> &lt;/simpleContent> &lt;/complexType> &lt;/element> &lt;/sequence> &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /> &lt;/restriction> &lt;/complexContent> &lt;/complexType> </pre>
	 */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "param"
    })
    public static class ParamList {

        /**
		 */
        @XmlElement(required = true)
        protected List<Param> param;
        /**
		 */
        @XmlAttribute(required = true)
        protected int id;

        /**
		 * Gets the value of the param property. <p> This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the param property. <p> For example, to add a new item, do as follows: <pre> getParam().add(newItem); </pre> <p> Objects of the following type(s) are allowed in the list  {@link Param   } 
		 * @uml.property  name="param"
		 */
        public List<Param> getParam() {
            if (param == null) {
                param = new ArrayList<Param>();
            }
            return this.param;
        }

        /**
		 * Gets the value of the id property.
		 * @uml.property  name="id"
		 */
        public int getId() {
            return id;
        }

        /**
		 * Sets the value of the id property.
		 * @uml.property  name="id"
		 */
        public void setId(int value) {
            this.id = value;
        }


        /**
		 * <p>Java class for anonymous complex type. <p>The following schema fragment specifies the expected content contained within this class. <pre> &lt;complexType> &lt;simpleContent> &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string"> &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /> &lt;/extension> &lt;/simpleContent> &lt;/complexType> </pre>
		 */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Param {

            /**
			 */
            @XmlValue
            protected String value;
            /**
			 */
            @XmlAttribute(required = true)
            protected String id;

            /**
			 * Gets the value of the value property.
			 * @return   possible object is  {@link String   }  
			 * @uml.property  name="value"
			 */
            public String getValue() {
                return value;
            }

            /**
			 * Sets the value of the value property.
			 * @param value   allowed object is  {@link String   }  
			 * @uml.property  name="value"
			 */
            public void setValue(String value) {
                this.value = value;
            }

            /**
			 * Gets the value of the id property.
			 * @return   possible object is  {@link String   }  
			 * @uml.property  name="id"
			 */
            public String getId() {
                return id;
            }

            /**
			 * Sets the value of the id property.
			 * @param value   allowed object is  {@link String   }  
			 * @uml.property  name="id"
			 */
            public void setId(String value) {
                this.id = value;
            }

        }

    }


    /**
	 * <p>Java class for anonymous complex type. <p>The following schema fragment specifies the expected content contained within this class. <pre> &lt;complexType> &lt;complexContent> &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"> &lt;attribute name="ip" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /> &lt;attribute name="port" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /> &lt;/restriction> &lt;/complexContent> &lt;/complexType> </pre>
	 */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class ReceiveInfo {

        /**
		 */
        @XmlAttribute(required = true)
        protected String ip;
        /**
		 */
        @XmlAttribute(required = true)
        protected String port;

        /**
		 * Gets the value of the ip property.
		 * @return   possible object is  {@link String   }  
		 * @uml.property  name="ip"
		 */
        public String getIp() {
            return ip;
        }

        /**
		 * Sets the value of the ip property.
		 * @param value   allowed object is  {@link String   }  
		 * @uml.property  name="ip"
		 */
        public void setIp(String value) {
            this.ip = value;
        }

        /**
		 * Gets the value of the port property.
		 * @return   possible object is  {@link String   }  
		 * @uml.property  name="port"
		 */
        public String getPort() {
            return port;
        }

        /**
		 * Sets the value of the port property.
		 * @param value   allowed object is  {@link String   }  
		 * @uml.property  name="port"
		 */
        public void setPort(String value) {
            this.port = value;
        }

    }


    /**
	 * <p>Java class for anonymous complex type. <p>The following schema fragment specifies the expected content contained within this class. <pre> &lt;complexType> &lt;complexContent> &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"> &lt;sequence> &lt;element name="return_row" maxOccurs="unbounded" minOccurs="0"> &lt;complexType> &lt;complexContent> &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"> &lt;sequence> &lt;element name="return_col" maxOccurs="unbounded" minOccurs="0"> &lt;complexType> &lt;simpleContent> &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string"> &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /> &lt;/extension> &lt;/simpleContent> &lt;/complexType> &lt;/element> &lt;/sequence> &lt;/restriction> &lt;/complexContent> &lt;/complexType> &lt;/element> &lt;/sequence> &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /> &lt;/restriction> &lt;/complexContent> &lt;/complexType> </pre>
	 */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "returnRow"
    })
    public static class ReturnList {

        /**
		 */
        @XmlElement(name = "return_row", required = true)
        protected List<ReturnRow> returnRow;
        /**
		 */
        @XmlAttribute(required = true)
        protected int id;

        /**
		 * Gets the value of the returnRow property. <p> This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the returnRow property. <p> For example, to add a new item, do as follows: <pre> getReturnRow().add(newItem); </pre> <p> Objects of the following type(s) are allowed in the list  {@link ReturnRow   } 
		 * @uml.property  name="returnRow"
		 */
        public List<ReturnRow> getReturnRow() {
            if (returnRow == null) {
                returnRow = new ArrayList<ReturnRow>();
            }
            return this.returnRow;
        }

        /**
		 * Gets the value of the id property.
		 * @uml.property  name="id"
		 */
        public int getId() {
            return id;
        }

        /**
		 * Sets the value of the id property.
		 * @uml.property  name="id"
		 */
        public void setId(int value) {
            this.id = value;
        }


        /**
		 * <p>Java class for anonymous complex type. <p>The following schema fragment specifies the expected content contained within this class. <pre> &lt;complexType> &lt;complexContent> &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"> &lt;sequence> &lt;element name="return_col" maxOccurs="unbounded" minOccurs="0"> &lt;complexType> &lt;simpleContent> &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string"> &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /> &lt;/extension> &lt;/simpleContent> &lt;/complexType> &lt;/element> &lt;/sequence> &lt;/restriction> &lt;/complexContent> &lt;/complexType> </pre>
		 */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "returnCol"
        })
        public static class ReturnRow {

            /**
			 */
            @XmlElement(name = "return_col", required = true)
            protected List<ReturnCol> returnCol;

            /**
			 * Gets the value of the returnCol property. <p> This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the returnCol property. <p> For example, to add a new item, do as follows: <pre> getReturnCol().add(newItem); </pre> <p> Objects of the following type(s) are allowed in the list  {@link ReturnCol   } 
			 * @uml.property  name="returnCol"
			 */
            public List<ReturnCol> getReturnCol() {
                if (returnCol == null) {
                    returnCol = new ArrayList<ReturnCol>();
                }
                return this.returnCol;
            }


            /**
			 * <p>Java class for anonymous complex type. <p>The following schema fragment specifies the expected content contained within this class. <pre> &lt;complexType> &lt;simpleContent> &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string"> &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /> &lt;/extension> &lt;/simpleContent> &lt;/complexType> </pre>
			 */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class ReturnCol {

                /**
				 */
                @XmlValue
                protected String value;
                /**
				 */
                @XmlAttribute(required = true)
                protected String id;

                /**
				 * Gets the value of the value property.
				 * @return   possible object is  {@link String   }  
				 * @uml.property  name="value"
				 */
                public String getValue() {
                    return value;
                }

                /**
				 * Sets the value of the value property.
				 * @param value   allowed object is  {@link String   }  
				 * @uml.property  name="value"
				 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
				 * Gets the value of the id property.
				 * @return   possible object is  {@link String   }  
				 * @uml.property  name="id"
				 */
                public String getId() {
                    return id;
                }

                /**
				 * Sets the value of the id property.
				 * @param value   allowed object is  {@link String   }  
				 * @uml.property  name="id"
				 */
                public void setId(String value) {
                    this.id = value;
                }

            }

        }

    }


    /**
	 * <p>Java class for anonymous complex type. <p>The following schema fragment specifies the expected content contained within this class. <pre> &lt;complexType> &lt;complexContent> &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"> &lt;attribute name="ip" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /> &lt;attribute name="port" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /> &lt;/restriction> &lt;/complexContent> &lt;/complexType> </pre>
	 */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class SendInfo {

        /**
		 */
        @XmlAttribute(required = true)
        protected String ip;
        /**
		 */
        @XmlAttribute(required = true)
        protected String port;

        /**
		 * Gets the value of the ip property.
		 * @return   possible object is  {@link String   }  
		 * @uml.property  name="ip"
		 */
        public String getIp() {
            return ip;
        }

        /**
		 * Sets the value of the ip property.
		 * @param value   allowed object is  {@link String   }  
		 * @uml.property  name="ip"
		 */
        public void setIp(String value) {
            this.ip = value;
        }

        /**
		 * Gets the value of the port property.
		 * @return   possible object is  {@link String   }  
		 * @uml.property  name="port"
		 */
        public String getPort() {
            return port;
        }

        /**
		 * Sets the value of the port property.
		 * @param value   allowed object is  {@link String   }  
		 * @uml.property  name="port"
		 */
        public void setPort(String value) {
            this.port = value;
        }

    }


    /**
	 * <p>Java class for anonymous complex type. <p>The following schema fragment specifies the expected content contained within this class. <pre> &lt;complexType> &lt;complexContent> &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"> &lt;sequence> &lt;element name="work_key" type="{http://www.w3.org/2001/XMLSchema}string"/> &lt;element name="work_div" type="{http://www.w3.org/2001/XMLSchema}string"/> &lt;element name="work_code" type="{http://www.w3.org/2001/XMLSchema}string"/> &lt;/sequence> &lt;/restriction> &lt;/complexContent> &lt;/complexType> </pre>
	 */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "workKey",
        "workDiv",
        "workCode"
    })
    public static class WorkInfo {

        /**
		 */
        @XmlElement(name = "work_key", required = true)
        protected String workKey;
        /**
		 */
        @XmlElement(name = "work_div", required = true)
        protected String workDiv;
        /**
		 */
        @XmlElement(name = "work_code", required = true)
        protected String workCode;

        /**
		 * Gets the value of the workKey property.
		 * @return   possible object is  {@link String   }  
		 * @uml.property  name="workKey"
		 */
        public String getWorkKey() {
            return workKey;
        }

        /**
		 * Sets the value of the workKey property.
		 * @param value   allowed object is  {@link String   }  
		 * @uml.property  name="workKey"
		 */
        public void setWorkKey(String value) {
            this.workKey = value;
        }

        /**
		 * Gets the value of the workDiv property.
		 * @return   possible object is  {@link String   }  
		 * @uml.property  name="workDiv"
		 */
        public String getWorkDiv() {
            return workDiv;
        }

        /**
		 * Sets the value of the workDiv property.
		 * @param value   allowed object is  {@link String   }  
		 * @uml.property  name="workDiv"
		 */
        public void setWorkDiv(String value) {
            this.workDiv = value;
        }

        /**
		 * Gets the value of the workCode property.
		 * @return   possible object is  {@link String   }  
		 * @uml.property  name="workCode"
		 */
        public String getWorkCode() {
            return workCode;
        }

        /**
		 * Sets the value of the workCode property.
		 * @param value   allowed object is  {@link String   }  
		 * @uml.property  name="workCode"
		 */
        public void setWorkCode(String value) {
            this.workCode = value;
        }

    }

}
